// reducers/btn-click
export const TOGGLE_CATEGORY_MODAL = 'TOGGLE_CATEGORY_MODAL';
export const CLICK_EDIT_CATEGORY = 'CLICK_EDIT_CATEGORY';
export const CLICK_DELETE_CATEGORY = 'CLICK_DELETE_CATEGORY';
export const TOGGLE_TASK_MODAL = 'TOGGLE_TASK_MODAL';
export const CLICK_ADD_NESTED_CATEGORY = 'CLICK_ADD_NESTED_CATEGORY';
export const CLOSE_ALL_BTN = 'CLOSE_ALL_BTN';

// reducers/categories
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_NESTED_CATEGORY = 'ADD_NESTED_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const TOGGLE_COLLAPSE_CATEGORY = 'TOGGLE_COLLAPSE_CATEGORY';
export const OPEN_COLLAPSE_CATEGORY = 'OPEN_COLLAPSE_CATEGORY';

// reducers/categoriesId
export const SAVE_CATEGORY_ID = 'SAVE_CATEGORY_ID';
export const DELETE_CATEGORY_ID = 'DELETE_CATEGORY_ID';

// reducers/categoryTree
export const SAVE_CATEGORY_TREE = 'SAVE_CATEGORY_TREE';

// reducers/edit-task
export const SAVE_TASK_ID_TO_EDIT = 'SAVE_TASK_ID_TO_EDIT';
export const SAVE_CHECKBOX_TO_EDIT = 'SAVE_CHECKBOX_TO_EDIT';
export const CHANGE_CHECKBOX_TO_EDIT_TASK = 'CHANGE_CHECKBOX_TO_EDIT_TASK';
export const OPEN_NOTIFICATION = 'OPEN_NOTIFICATION';
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';
export const SHOW_VALID_NOTIFICATION_EDIT_TASK = 'SHOW_VALID_NOTIFICATION_EDIT_TASK';
export const SHOW_NOT_VALID_NOTIFICATION_EDIT_TASK = 'SHOW_NOT_VALID_NOTIFICATION_EDIT_TASK';
export const SAVE_CATEGORY_ID_TO_MOVE_TASK = 'SAVE_CATEGORY_ID_TO_MOVE_TASK';
export const DELETE_CATEGORY_ID_TO_MOVE_TASK = 'DELETE_CATEGORY_ID_TO_MOVE_TASK';

// reducers/filter
export const SAVE_FILTER_TITLE = 'SAVE_FILTER_TITLE';
export const TOGGLE_FILTER = 'TOGGLE_FILTER';

// reducers/modal
export const TOGGLE_MODAL = 'TOGGLE_MODAL';

// reducers/progressbar
export const UPDATE_PROGRESS = 'UPDATE_PROGRESS';

// reducers/tasks
export const ADD_TASK = 'ADD_TASK';
export const TOGGLE_CHECKBOX_EDIT_TASK = 'TOGGLE_CHECKBOX_EDIT_TASK';
export const UPDATE_TASK_TITLE = 'UPDATE_TASK_TITLE';
export const UPDATE_TASK_DESCRIPTION = 'UPDATE_TASK_DESCRIPTION';
export const UPDATE_TACK_CHECKBOX = 'UPDATE_TACK_CHECKBOX';
export const MOVE_TASK = 'MOVE_TASK';

// reducers/title-to-delete
export const SAVE_TITLE_TO_DELETE = 'SAVE_TITLE_TO_DELETE';
export const SHOW_NOT_VALID_NOTIFICATION = 'SHOW_NOT_VALID_NOTIFICATION';
export const SHOW_VALID_NOTIFICATION = 'SHOW_VALID_NOTIFICATION';